services:
  - type: web
    name: app
    env: node
    build:
      context: .
      dockerfile: Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mydatabase
          property: connectionString
    envFilePath: ./.env
    port: 3000
    dependsOn:
      - db
    autoDeploy: true
    watch:
      - path: ./package.json
        action: rebuild
      - path: ./pnpm-lock.yaml
        action: rebuild
      - path: ./src
        target: /app
        action: sync

  - type: postgres
    name: db
    databaseName: mydatabase
    user: myuser
    password: mypassword
    port: 5432
    volume:
      name: postgres_data
      mountPath: /var/lib/postgresql/data